# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: catest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: caproduction
  pool: 5
  timeout: 5000
  username: postgres
  password: sql
